# relation behavior config

level:
    label: level
    view:
        list: $/khalil/elearning/models/level/columns.yaml        
        form: $/khalil/elearning/models/level/fields.yaml
        toolbarButtons: create|remove
    manage:
        showSearch: true
        recordsPerPage: 10        
        list: $/khalil/elearning/models/level/columns.yaml        
        form: $/khalil/elearning/models/level/fields.yaml

subject:
    label: subject
    view:       
        form: $/khalil/elearning/models/subject/fields.yaml
        toolbarButtons: create|remove
    manage:       
        list: $/khalil/elearning/models/subject/columns.yaml        
        form: $/khalil/elearning/models/subject/fields.yaml

topics:
    label: topics
    view:       
        list: $/khalil/elearning/models/topic/columns.yaml        
        form: $/khalil/elearning/models/topic/fields.yaml        
        toolbarButtons: create|remove
    manage:              
        form: $/khalil/elearning/models/topic/fields.yaml        
        list: $/khalil/elearning/models/topic/columns.yaml        
